### ISSUE TITLE
running finetuning.py AttributeError: 'numpy.ndarray' object has no attribute 'x'

### ISSUE THREAD

**Issue by Jim2016713** [bigboNed3/chinese_ulmfit#1]

**Comment by practicingman** [comment]
> _No description provided._

没法重现啊。你是conda env create -f env.yml建的虚拟环境吗？

**Comment by DragonAndSky** [comment]
请问学习率方面是自己设置的吗？与官方论文中的似乎不同，这样做的效果更好？

**Comment by Annielina** [comment]
> 请问学习率方面是自己设置的吗？与官方论文中的似乎不同，这样做的效果更好？

您好 ，请问您有测试官方所说的2.6倍的那个学习率吗
