### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216  on fastai==0.7.0

### ISSUE THREAD

**Issue by SeekPoint** [bigboNed3/chinese_ulmfit#3]
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/chinese_ulmfit$ python3.6 pretraining.py --input_file=tmp/wiki2018-11-14.ids.npy --mapping_file=tmp/wiki2018-11-14.mapping.pkl --dir_path=tmp
Traceback (most recent call last):
  File "pretraining.py", line 2, in <module>
    from fastai.text import *
  File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/text.py", line 1, in <module>
    from .core import *
  File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/core.py", line 1, in <module>
    from .imports import *
  File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/imports.py", line 2, in <module>
    import PIL, os, numpy as np, math, collections, threading, json, bcolz, random, scipy, cv2
  File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/bcolz/__init__.py", line 76, in <module>
    from bcolz.carray_ext import (
  File "__init__.pxd", line 885, in init bcolz.carray_ext
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/chinese_ulmfit$

**Comment by practicingman** [comment]
> (.venv) ub16c9@ub16c9-gpu:/ub16_prj/chinese_ulmfit$ python3.6 pretraining.py --input_file=tmp/wiki2018-11-14.ids.npy --mapping_file=tmp/wiki2018-11-14.mapping.pkl --dir_path=tmp
> Traceback (most recent call last):
> File "pretraining.py", line 2, in 
> from fastai.text import *
> File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/text.py", line 1, in 
> from .core import *
> File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/core.py", line 1, in 
> from .imports import *
> File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/fastai/imports.py", line 2, in 
> import PIL, os, numpy as np, math, collections, threading, json, bcolz, random, scipy, cv2
> File "/home/ub16c9/ub16_prj/chinese_ulmfit/.venv/lib/python3.6/site-packages/bcolz/**init**.py", line 76, in 
> from bcolz.carray_ext import (
> File "**init**.pxd", line 885, in init bcolz.carray_ext
> ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
> (.venv) ub16c9@ub16c9-gpu:/ub16_prj/chinese_ulmfit$

seems the problem is related to numpy. try use the same version of numpy described in env.yml?

**Comment by SeekPoint** [comment]
pip3.6 install numpy==1.15.4 doesn't work yet

**Comment by tc-yue** [comment]
same problem，我是按照yml创建的新环境，似乎是numpy的问题。
我把numpy更新到最新，然后在finetune时又出现了AttributeError: rint when using numpy.round，
似乎是fastai的model.py中np.round中传入values的dtype问题。
`
ep_vals[epoch]=list(np.round(values, decimals))
`

**Comment by Ernie1** [comment]
I modify the fastai package code in `model.py` as below and the wrong disappears. And my numpy is the latest version.
```
def append_stats(ep_vals, epoch, values, decimals=6):
    ep_vals[epoch]=list(np.round(np.array(values, dtype=np.double), decimals))
    return ep_vals

def print_stats(epoch, values, decimals=6):
    layout = "{!s:^10}" + " {!s:10}" * len(values)
    values = [epoch] + list(np.round(np.array(values, dtype=np.double), decimals))
    print(layout.format(*values))
```

**Comment by winnie0** [comment]
> pip3.6 install numpy==1.15.4 doesn't work yet

Maybe the libgcc version is too low,  causing conflict with numpy，improve the version of libgcc can fit it. I use the env.yml to install environment, but remove the version number after libgcc and numpy. It works. :)

**Comment by Annielina** [comment]
> same problem，我是按照yml创建的新环境，似乎是numpy的问题。
> 我把numpy更新到最新，然后在finetune时又出现了AttributeError: rint when using numpy.round，
> 似乎是fastai的model.py中np.round中传入values的dtype问题。
> ep_vals[epoch]=list(np.round(values, decimals))

您好，请问这个问题您最后解决了吗
