### ISSUE TITLE
segment_wiki是否有优化的余地? 感觉速度慢到发指

### ISSUE THREAD

**Issue by RadioSura** [bigboNed3/chinese_ulmfit#5]

**Comment by hanghr** [comment]
我是先用分词，然后再修改segment_wiki的部分代码，速度还可以

**Comment by Annielina** [comment]
> 我是先用分词，然后再修改segment_wiki的部分代码，速度还可以

您好，能具体说说怎么弄的吗，我的分词维基百科就已经内存爆了（8G）
